# Generated by Django 4.0.6 on 2024-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_friendsrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsrequests',
            name='status',
            field=models.CharField(choices=[('CRE', 'Created'), ('APP', 'Approved'), ('REJ', 'REJECTED')], default='CRE', max_length=3),
        ),
    ]
